version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: auth_bdd
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root   # Mot de passe de l'utilisateur root
      MYSQL_DATABASE: auth_poc            # Nom de la base de données
      MYSQL_USER: mysql               # Utilisateur de la base de données
      MYSQL_PASSWORD: mysql          # Mot de passe de l'utilisateur
    ports:
      - "3306:3306"                       # Expose le port MySQL
    volumes:
      - db_data:/var/lib/mysql            # Volume pour persister les données

volumes:
  db_data:
