services:
  angular:
    build:
      context: ./front_auth
    ports:
      - "4200:4200"
    depends_on:
      - nestjs
    networks:
      - app-network
    volumes:
      - ./front_auth:/app
      - /app/node_modules

  nestjs:
    build:
      context: ./backend_auth
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST= db
      - DATABASE_PORT= 3306
      - DATABASE_USER= ${DB_DATABASE_USER}
      - DATABASE_PASSWORD= ${DB_PASSWORD}
      - DATABASE_NAME= ${DB_DATABASE_NAME}
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: auth_bdd
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE_NAME}
      MYSQL_USER: ${DB_DATABASE_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3306:3306"
    command: [
      "--default-authentication-plugin=mysql_native_password"
    ]
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
